### ISSUE TITLE
Botones sin accion

### ISSUE THREAD

**Issue by NicoGonzalez94** [juanchyquintana/restauranteFrontend#75]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que los botones redirijan a dicho sitio o una page 404.

## Resultado actual

• Los botones no cumplen ninguna accion.

## Captura

![image](https://github.com/juanchyquintana/restauranteFrontend/assets/166792979/b4ea2a2c-9706-412e-aa0c-e860b5e9f66b)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by juanchyquintana** [comment]
Buenas tardes, Nico! Muchas gracias por tu corrección! En breves completáremos todos los puntos que nos marcaste. Este fue completado por @kstephantorres. Saludos!
