### ISSUE TITLE
Productos

### ISSUE THREAD

**Issue by NicoGonzalez94** [juanchyquintana/restauranteFrontend#76]
## Proceso

1. Ingrese a la pagina.
2. Quise ver algunos productos.

## Resultado esperado

• Que no se muestre informacion por consola del producto.

## Resultado actual

• Al ingresar a un producto se muestra informacion del mismo por consola.

## Captura

![image](https://github.com/juanchyquintana/restauranteFrontend/assets/166792979/377e1ff7-4ce3-4cd8-a3d7-ac5d618e14a6)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by juanchyquintana** [comment]
Buenas tardes, Nico! Muchas gracias por tu corrección! En breves completáremos todos los puntos que nos marcaste. Este fue completado por @juanchyquintana. Saludos!
